---
title: "Plot_output"
author: "Team CDMA"
date: '2022-07-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
library(igraph)
library(networkD3)
library(visNetwork)
library(tidytext) #install.packages("tidytext")
library(wordcloud) #install.packages("wordcloud")
library(ggtext)
library(ggalt)
library(ggthemes)
library(ggpubr)

IEC_data <- read_csv('sample_data.csv')

IEC_data %>% 
  mutate(across(everything(), as.character)) %>% 
  pivot_longer(!IE_code, 
               names_to = 'Attribute',
               values_to = 'Attrib_value') %>% 
  relocate(Attribute, .after = 3) -> long_data

# graph object
g <- graph_from_data_frame(long_data)

# Long format all columns
long_data2 <- IEC_data %>% 
  mutate(across(everything(), as.character)) %>% 
  pivot_longer(everything(), 
               names_to = 'Attribute',
               values_to = 'Attrib_value') %>% 
  distinct()

# Re-order using joins
V(g)$att_type <- V(g)$name %>% 
  as.data.frame() %>% 
  set_names('name') %>% 
  inner_join(long_data2, by = c("name" = "Attrib_value")) %>% 
  pull(Attribute)

V(g)$color <- c('steel blue', 'orange')[1 + (V(g)$att_type == 'IE_code')]

V(g)$shape <- c("square", "circle")[(V(g)$att_type == 'IE_code')+1]

```

Plot the object
```{r echo=FALSE,fig.align='center', fig.width=7}
visIgraph(g)
```
